### ISSUE TITLE
docs(formation): example of error handling

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#4]
Context

- field is invalid and user is editing/ tabs out
- field is invalid and form is submitted

Approach

- How to show field is invalid - formatting rules? e.g. turn box red
- How to show field is invalid - error message/ completion advice?
- How to show form is invalid - error messagging

**Comment by shanereid** [comment]
@mikerkeating 

Any form you generate will automatically be validated, however formation just uses css classes, and you can decide what to do with the css classes. 

Formation will add `fn-dirty`, `fn-valid`, and `fn-invalid` classes to all fields depending on certain things.
- `fn-dirty` will be added to the `form-group` and/or `label` container of each element that requires validation when it is dirtied.
- `fn-valid` will be added to all valid fields
- `fn-invalid` will be added to all invalid fields

This can be used in a simple but effective way with CSS, such as:

```
.fn-invalid input, .fn-invalid select {
	border: 1px solid #F00;
}
```

But can be more complicated, such as you putting your validation messages within a template so it's encased by the form-group div, and then using something like

```
.error-message {
    display: none;
}

.fn-invalid .error-message {
    display: block;
}
```

which will reveal all elements with `error-message` class when the field is invalid otherwise hide it.
